### ISSUE TITLE
Installing Addons

### ISSUE THREAD

**Issue by abtxu** [Citavi/C6-Add-Ons-and-Online-Sources#9]
Hi Lutz, 

Thank you so much for developing these add-ons. My initial interest is about transferring Acrobat-Citavi  pdf comments/annotations, which leads me to your project.

I followed your instruction on "How do I install an addon?" and created a new folder AddOns in the installed folder of Citavi (F:\Program Files (x86)\Citavi 6) and put all the unzipped files into that file. Unfortunately the installation does not work. I was wondering how to fix it and I would be really appreciate it if you could help. 

I noted that the addons from Citavi themselves are files like "TomatoTimerAddon.dll" which I did not find in the downloaded zip files. 

Thank you in advance.

**Comment by lutz** [comment]
Hello abtxu,

thanks for your message. Unfortunately it is not quite clear whether you have landed in the right place. This repository contains the public source code of the add-ons published by Swiss Academic Software for Citavi. These add-ons can be installed using the appropriate Citavi feature. Further information can be found [here](https://www1.citavi.com/sub/manual6/en/index.html?installing_add-ons.html). If you have any questions, please contact [Support](https://www.citavi.com/de/support/uebersicht) directly. After your explanation I assume that you came from my private [Add-ons](https://github.com/lutz/CitaviProjects), for which Swiss Academic Software does not provide support. If this is the case, I would ask you to open an issue in the corresponding private repository, whose links you can find on the [overview page](https://github.com/lutz/CitaviProjects).

With kind regards
[Lutz](https://github.com/lutz)
